import { z } from 'zod';
export const db = {} as any;
export const collection = (() => {}) as any;
export const doc = (() => {}) as any;
export const setDoc = (() => {}) as any;
export const getDoc = (() => {}) as any;
export const updateDoc = (() => {}) as any;
export const deleteDoc = (() => {}) as any;
export const query = (() => {}) as any;
export const where = (() => {}) as any;
export const getDocs = (() => {}) as any;